id: P004448
initial_creation_type: ocr
source_metadata:
  id: bdr:W23376
  title: མ་འོངས་ལུང་བསྟན་དངུལ་དཀར་མེ་ལོང
  author: ''
  volumes:
    e6beecbec93541e180005ebbb0e1b6a3:
      image_group_id: I1558
      title: ''
      volume_number: 1
      total_pages: 118
      base_file: v001.txt
