id: I1164F4B2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T08:58:22+00:00'
last_modified: '2022-06-08T04:37:23.870619+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W23376
  title: མ་འོངས་ལུང་བསྟན་དངུལ་དཀར་མེ་ལོང
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    DB14:
      image_group_id: I1558
      title: ''
      total_pages: 118
      order: 1
      base_file: DB14.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
